services:
  cronicle:
    image: soulteary/cronicle:0.9.80
    restart: unless-stopped
    hostname: cronicle
    environment:
      TZ: Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker/cronicle/data:/opt/cronicle/data
      - /docker/cronicle/logs:/opt/cronicle/logs
      - /docker/cronicle/plugins:/opt/cronicle/plugins
