services:
  cronicle:
    image: soulteary/cronicle:0.9.80
    restart: unless-stopped
    hostname: cronicle
    environment:
      TZ: Europe/Paris
    ports:
      - "3012"
    volumes:
      - cronicle_data:/opt/cronicle/data
      - cronicle_logs:/opt/cronicle/logs
      - cronicle_plugins:/opt/cronicle/plugins

volumes:
  cronicle_data:
  cronicle_logs:
  cronicle_plugins:
